import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-fixed bg-cover bg-center`}
        style={{
          backgroundImage: "url('/images/background-image/artistic-blurry-colorful-wallpaper-background-5.jpg')",
        }}
      >
        <div className="bg-black/50 backdrop-blur-sm min-h-screen">
          {children}
        </div>
      </body>
    </html>
  )
}
